### PR TITLE
fix: fixed resizable table with form threw error in dev #1506

### LINKED ISSUE #1506: [BUG] resizable Table 与 form 同时使用，dev 环境下 deepClone 报错
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Table

### Semi Version

latest

### Current Behavior

复现现场：https://codesandbox.io/s/fix-table-resizable-bug-8gzo3z

image

报错堆栈

img_v2_55d482b9-0c35-4d45-bb8f-a4a41dfd547g

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### ReproducibleCode

```markdown
import { Table } from "@douyinfe/semi-ui";

export default function App() {
  return (
    <div className="App">
      <form />
      <Table
        resizable
        dataSource={[]}
        columns={[
          {
            dataIndex: "dau",
            title: <div>ccc</div>,
            width: 300
          }
        ]}
      />
    </div>
  );
}
```

### Environment

```markdown
- OS:
- browser:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by shijiatongxue**
[中文模板 / Chinese Template](https://github.com/DouyinFE/semi-design/blob/main/.github/PULL_REQUEST_TEMPLATE.zh-CN.md)

- [x] I have read and followed [Pull Request Guidelines](https://github.com/DouyinFE/semi-design/blob/main/CONTRIBUTING-en-US.md#pull-request-guidelines) of the contributing guide.

### What kind of change does this PR introduce? (check at least one)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update
 - [ ] Refactor
 - [ ] Test Case
 - [ ] TypeScript definition update
 - [ ] Document improve
 - [ ] CI/CD improve
 - [ ] Branch sync
 - [ ] Other, please describe:

### PR description

Fixes #1506 

顺便修改了一下 eslint-plugin-semi-design 在 story 引入 @douyinfe/semi-ui 时报引用错误问题

### Changelog
🇨🇳 Chinese
- Fix: 修复 resizable Table 与 form 同时使用在 dev 环境下报错问题 #1506

---

🇺🇸 English
- Fix: Fix the problem of using resizable Table and form at the same time in the dev environment to report an error #1506

### Checklist
- [x] Test or no need
- [x] Document or no need
- [x] Changelog or no need

### Other
- [ ] Skip Changelog

### CODE REVIEW

File: packages/semi-foundation/table/utils.ts [hunk 1]
```diff
@@ -65,6 +65,11 @@ export function mergeColumns(oldColumns: any[] = [], newColumns: any[] = [], key
     const finalColumns: any[] = [];
```
Comment (pointhalo) [inline packages/semi-foundation/table/utils.ts:65]: 这里的  mergeColumns 还有用吗？

Comment (pointhalo) [reply packages/semi-foundation/table/utils.ts:65]: 如果不再使用，应该注释掉？

**Comment by pointhalo** [comment]
v2.31.2 这个还是有问题：https://codesandbox.io/s/sad-fermat-4uu8xg?file=/src/App.js
