### PR TITLE
fix(toast): update TypeScript definition of Toast

### LINKED ISSUE #166: Toast 无类型提示
### Which Component 出现bug的组件
  - Toast

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  -  有类型提示

### Actual result 实际的结果是什么
  -  无类型提示

### Reproducible code 复现代码
```
import { Toast } from '@douyinfe/semi-ui'; // Toast is any type
```

### Additional information 补充说明
- 应该是 `packages/semi-ui/toast/index.tsx:34` line 的 any

### PR DESCRIPTION
**Pull request by zwlafk**
[中文模板 / Chinese Template](https://github.com/DouyinFE/semi-design/blob/main/.github/PULL_REQUEST_TEMPLATE.zh-CN.md)

- [x] I have read and followed [Pull Request Guidelines](https://github.com/DouyinFE/semi-design/blob/main/CONTRIBUTING-en-US.md#pull-request-guidelines) of the contributing guide.

### What kind of change does this PR introduce? (check at least one)

 - [x] TypeScript definition update

### PR description

Fixes #166

### Changelog
🇨🇳 Chinese
- 修复 Toast 的类型定义

---

🇺🇸 English
- Fix TypeScript definition of Toast 

### Checklist
- [X] Test or no need
- [x] Document or no need
- [X] Changelog or no need

### CODE REVIEW

File: packages/semi-ui/toast/index.tsx [hunk 1]
```diff
@@ -30,199 +30,203 @@ export {
...
+const createBaseToast = () => class ToastList extends BaseComponent<ToastListProps, ToastListState> {
+    static ref: ToastList;
+    static useToast: typeof useToast;
+    static defaultOpts: ToastProps & { motion: Motion } = {
+        motion: true,
+        zIndex: 1010,
+    };
+    static propTypes = {
+        content: PropTypes.node,
+        duration: PropTypes.number,
```
Comment (shijiatongxue) [inline packages/semi-ui/toast/index.tsx:42]:
```suggestion
        duration: PropTypes.test,
```

File: packages/semi-ui/toast/index.tsx [hunk 2]
```diff
@@ -30,199 +30,203 @@ export {
...
-                }
-                if (typeof opts.duration === 'number') {
-                    ToastList.defaultOpts.duration = opts.duration;
-                }
-                if (typeof opts.getPopupContainer === 'function') {
-                    ToastList.defaultOpts.getPopupContainer = opts.getPopupContainer;
-                }
-            }
+    static success(opts: ToastProps) {
+        if (typeof opts === 'string') {
```
Comment (wuhw) [inline packages/semi-ui/toast/index.tsx:155]: 这里可以是string类型，为啥类型定义又没有string类型呢
