### PR TITLE
fix(table): resizable column width bug #650

### LINKED ISSUE #650: [Table]动态修改 columns ，列宽设置失效
### Which Component 出现bug的组件
  - Table

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 动态减少列，不影响其他指定宽度的列

### Actual result 实际的结果是什么
  - 减少列时，第一列宽度过大

### Steps to reproduce 复现步骤
  - 初始状态，第一列宽度 设定为 300
image
  - 点击减少一列，宽度变成 344
image

### Reproducible code 复现代码

https://codesandbox.io/s/autumn-fast-h0e2hx?file=/src/App.js

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

### PR DESCRIPTION
**Pull request by shijiatongxue**
[中文模板 / Chinese Template](https://github.com/DouyinFE/semi-design/blob/main/.github/PULL_REQUEST_TEMPLATE.zh-CN.md)

- [x] I have read and followed [Pull Request Guidelines](https://github.com/DouyinFE/semi-design/blob/main/CONTRIBUTING-en-US.md#pull-request-guidelines) of the contributing guide.

### What kind of change does this PR introduce? (check at least one)

 - [x] Bugfix

### PR description

Fixes #650

问题原因见 #650

### Changelog
🇨🇳 Chinese
- Fix: 修复 resizable Table 动态删除列时列宽计算错误问题 #650

---

🇺🇸 English
- Fix: fixed resizable Table columns width bug when update `columns` #650

### Checklist
- [ ] Test or no need
- [ ] Document or no need
- [ ] Changelog or no need

### Other
- [ ] Skip Changelog

### CODE REVIEW

File: packages/semi-foundation/table/utils.ts [hunk 1]
```diff
@@ -281,7 +281,9 @@ export function assignColumnKeys(columns: Record<string, any>[], childrenColumnN
     const sameLevelCols: Record<string, any>[] = [];
     each(columns, (column, index) => {
         if (column.key == null) {
-            column.key = `${level}-${index}`;
+            // if user give column a dataIndex, use it for backup
+            const _index = column.dataIndex || index;
```
Comment (zwlafk) [inline packages/semi-foundation/table/utils.ts:285]: dataIndex在column里可能有相同的情况吧

Comment (shijiatongxue) [reply packages/semi-foundation/table/utils.ts:285]: 确实
