### PR TITLE
fix: [Image] Put the declaration of the IntersectionObserver object in ImagePreview in componentdidMount to prevent errors in SSR scenarios

### LINKED ISSUE #1595: ImagePreview nextjs  2.34.1  IntersectionObserver is not defined
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

ImagePreview

### Semi Version

2.34.1

### Current Behavior

2.34.1, nextjs, build, error, IntersectionObserver is not defined

2.32.2 is ok

### Expected Behavior

build success

### Steps To Reproduce

1. nextjs
2. yarn build

### ReproducibleCode

```markdown
2.34.1
```

### Environment

```markdown
- OS: MacOS
- browser: Chrome
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by YyumeiZhang**
…iew unmount phase

[中文模板 / Chinese Template](https://github.com/DouyinFE/semi-design/blob/main/.github/PULL_REQUEST_TEMPLATE.zh-CN.md)

- [x] I have read and followed [Pull Request Guidelines](https://github.com/DouyinFE/semi-design/blob/main/CONTRIBUTING-en-US.md#pull-request-guidelines) of the contributing guide.

### What kind of change does this PR introduce? (check at least one)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update
 - [ ] Refactor
 - [ ] Test Case
 - [ ] TypeScript definition update
 - [ ] Document improve
 - [ ] CI/CD improve
 - [ ] Branch sync
 - [ ] Other, please describe:

### PR description

Fixes #1595 

### Changelog
🇨🇳 Chinese
- Fix:  将 ImagePreview 中的 IntersectionObserver 对象的声明放在 componentDidMount 而不是 constructor 中，防止 SSR 场景下出错 #1595 
---

🇺🇸 English
- Fix: Put the declaration of the IntersectionObserver object in ImagePreview in componentDidMount instead of constructor to prevent errors in SSR scenarios #1595 

### Checklist
- [x] Test or no need
- [x] Document or no need
- [x] Changelog or no need

### Other
- [ ] Skip Changelog

### Additional information

IntersectionObserver 的对象放在 constructor 中，是为了让 ImagePreview 下的 children 的 Image 能够拿到该 observer，在 Image 的 componentDidMount/ componentDidUpdata 中 props的src 变化时候能够被 observer 观察到。

由于IntersectionObserver 是浏览器 API， 放在 constructor 中会导致 SSR 场景下报错， 因此修改到 ImagePreview 的 componentDidMount 中，同时将在 componentDidUpdate 中对 children 进行监视，如果children 发生修改修改，则重新监听 img 元素

### CODE REVIEW

File: packages/semi-ui/image/preview.tsx [hunk 1]
```diff
@@ -81,21 +81,44 @@ export default class Preview extends BaseComponent<PreviewProps, PreviewState> {
...
+    componentDidMount() {
+        this.observerImages();
+    }
+
+    componentDidUpdate(prevProps) {
+        const prevChildren = React.Children.toArray(prevProps.children);
+        const currChildren = React.Children.toArray(this.props.children);
+    
+        if (!isEqual(prevChildren, currChildren)) {
+            this.observerImages();
```
Comment (shijiatongxue) [inline packages/semi-ui/image/preview.tsx:95]: 这里这样判断的话，父组件每次 render，这里都会重新监听一次？

Comment (shijiatongxue) [reply packages/semi-ui/image/preview.tsx:95]: 用 key 判断是不是更好一点
