### PR TITLE
fix(table): page back to one when columns change #381

### LINKED ISSUE #381: [Table] page back to one when columns change and Table re-render
### Which Component 出现bug的组件
  - Table

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - keep currentPage

### Actual result 实际的结果是什么
  - currentPage to one

### Reproducible code 复现代码
```
import React, { useState, useMemo } from 'react';
import { Table, Avatar } from '@douyinfe/semi-ui';
import * as dateFns from 'date-fns';

const DAY = 24 * 60 * 60 * 1000;
const figmaIconUrl = 'https://lf3-static.bytednsdoc.com/obj/eden-cn/ptlz_zlp/ljhwZthlaukjlkulzlp/figma-icon.png';
const pageSize = 5;

const getData = () => {
    const data = [];
    for (let i = 0; i < 46; i++) {
        const isSemiDesign = i % 2 === 0;
        const randomNumber = (i * 1000) % 199;
        data.push({
            key: '' + i,
            name: isSemiDesign ? `Semi Design 设计稿${i}.fig` : `Semi Pro 设计稿${i}.fig`,
            owner: isSemiDesign ? '姜鹏志' : '郝宣',
            size: randomNumber,
            updateTime: new Date().valueOf() + randomNumber * DAY,
            avatarBg: isSemiDesign ? 'grey' : 'red'
        });
    }
    return data;
};

const data = getData();
const pagination = {
    pageSize: 5,
    total: data.length,
};

function App() {
    const [dataSource, setData] = useState(data);
    const [loading, setLoading] = useState(false);
    const [currentPage, setPage] = useState(1);
    const [rowKeys, setRowKeys] = useState([]);

    const columns = [
        {
            title: '标题',
            dataIndex: 'name',
            width: 400,
            render: (text, record, index) => {
                return (
                    <div>
                        <Avatar size="small" shape="square" src={figmaIconUrl} style={{ marginRight: 12 }}></Avatar>
                        {text}
                    </div>
                );
            },
            filters: [
                {
                    text: 'Semi Design 设计稿',
                    value: 'Semi Design 设计稿',
                },
                {
                    text: 'Semi Pro 设计稿',
                    value: 'Semi Pro 设计稿',
                },
            ],
            onFilter: (value, record) => record.name.includes(value),
        },
        {
            title: '大小',
            dataIndex: 'size',
            sorter: (a, b) => a.size - b.size > 0 ? 1 : -1,
            render: (text) => `${text} KB`
        },
        {
            title: '所有者',
            dataIndex: 'owner',
            render: (text, record, index) => {
                return (
                    <div>
                        <Avatar size="small" color={record.avatarBg} style={{ marginRight: 4 }}>{typeof text === 'string' && text.slice(0, 1)}</Avatar>
                        {text}
                    </div>
                );
            }

        },
        {
            title: '更新日期',
            dataIndex: 'updateTime',
            sorter: (a, b) => a.updateTime - b.updateTime > 0 ? 1 : -1,
            render: (value) => {
                return dateFns.format(new Date(value), 'yyyy-MM-dd');
            }
        }
    ];

    return (
        <Table
            columns={columns}
            dataSource={dataSource}
            pagination={pagination}
            loading={loading}
            rowSelection={{
                onChange: rowKeys => setRowKeys(rowKeys),
                selectedRowKeys: rowKeys,
            }}
            scroll={{ y: 300, scrollToFirstRowOnChange: false }}
        />
    );
}

render(App);
```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

### PR DESCRIPTION
**Pull request by shijiatongxue**
[中文模板 / Chinese Template](https://github.com/DouyinFE/semi-design/blob/main/.github/PULL_REQUEST_TEMPLATE.zh-CN.md)

- [x] I have read and followed [Pull Request Guidelines](https://github.com/DouyinFE/semi-design/blob/main/CONTRIBUTING-en-US.md#pull-request-guidelines) of the contributing guide.

### What kind of change does this PR introduce? (check at least one)

 - [x] Bugfix

### PR description

Fixed #381

### Changelog
🇨🇳 Chinese
- Fix: 修复 columns 变化后分页器返回到第一页问题 #381

---

🇺🇸 English
- Fix: fixed page back to one when columns change bug #381

### Checklist
- [x] Test or no need
- [ ] Document or no need
- [x] Changelog or no need

### Other
- [ ] Skip Changelog

### CODE REVIEW

File: packages/semi-ui/table/Table.tsx [hunk 1]
```diff
@@ -547,17 +546,20 @@ class Table<RecordType extends Record<string, any>> extends BaseComponent<Normal
...
-                ...statePagination,
-                currentPage: isObject(propsPagination) && propsPagination.currentPage ? propsPagination.currentPage : 1,
-            } : statePagination;
 
             if (this.props.groupBy) {
                 states.groups = null;
             }
         }
 
+        // when dataSource has change, should reset currentPage
```
Comment (pointhalo) [inline packages/semi-ui/table/Table.tsx:555]: 这样改的话， 相比之前少了 stateCachedChildren !== prevState.cachedChildren 的判断。那如果 jsx 写法下，children更新了，现在并不会回到第一页对吗?

Comment (shijiatongxue) [reply packages/semi-ui/table/Table.tsx:555]: 是的

Comment (shijiatongxue) [reply packages/semi-ui/table/Table.tsx:555]: 无论是 children 还是 columns 变了，都不会回到第一页
