### PR TITLE
fix: Fixed the issue where the inputSlot format was not displayed whe…

### LINKED ISSUE #3049: [BUG] [AIChatInput] 内容粘贴不到空的 inputSlot 中
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Which Component

AIChatInput

### Semi Version

2.88.2

### Current Behavior

https://github.com/user-attachments/assets/b77d19c7-642d-4667-9172-996075a67c2b

### Expected Behavior

https://github.com/user-attachments/assets/f6e16223-b10b-4cd8-97d1-574836705b06

### Steps To Reproduce

_No response_

### ReproducibleCode

```markdown

```

### Environment

```markdown
- OS:
- browser:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by YyumeiZhang**
…n pasting content into an empty inputSlot

[中文模板 / Chinese Template](https://github.com/DouyinFE/semi-design/blob/main/.github/PULL_REQUEST_TEMPLATE.zh-CN.md)

- [x] I have read and followed [Pull Request Guidelines](https://github.com/DouyinFE/semi-design/blob/main/CONTRIBUTING-en-US.md#pull-request-guidelines) of the contributing guide.

### What kind of change does this PR introduce? (check at least one)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update
 - [ ] Refactor
 - [ ] Test Case
 - [ ] TypeScript definition update
 - [ ] Document improve
 - [ ] CI/CD improve
 - [ ] Branch sync
 - [ ] Other, please describe:

### PR description

Fixes #3049 

### Changelog
🇨🇳 Chinese
- Fix: 修复向空的 inputSlot 中粘贴内容时候，仅粘贴了文本，无 inputSlot 样式问题 #3049 
- Fix: 修复当选中 inputSlot 中的所有内容并粘贴内容时候，仅粘贴了文本，无 inputSlot 样式问题  #3049

---

🇺🇸 English
- Fix: Fixed an issue where pasting content into an empty inputSlot resulted in only text being pasted without displaying the inputSlot style #3049 
- Fix: Fixed an issue where, when pasting content after selecting all text in an inputSlot, the inputSlot would disappear. #3049 

### Checklist
- [x] Test or no need
- [x] Document or no need
- [x] Changelog or no need

### Other
- [ ] Skip Changelog

### CODE REVIEW

File: packages/semi-ui/aiChatInput/extension/plugins.ts [hunk 1]
```diff
@@ -412,12 +412,44 @@ export function handlePasteLogic(view: EditorView, event: ClipboardEvent) {
...
 
+/**
+ * 如果是 parentNode 是 input-slot，当里面内容仅为零宽字符时候
+ * 直接去掉零宽字符会导致 input-slot 消失，
+ * 因此将此行为处理成获取文字部分，将零宽字符替换为文字内容
+ * If the parentNode is input-slot, and the content inside is only zero-width characters...
+ * Removing zero-width characters directly will cause the input slot to disappear.
+ * Therefore, this paste behavior is processed to retrieve the text portion and replace the zero-width characters with the text content.
+ */
+export function specialPasteLogicForInputSlot(event: ClipboardEvent, $from: any, tr: Transaction, dispatch: (tr: Transaction) => void) {
```
Comment (YannLynn) [inline packages/semi-ui/aiChatInput/extension/plugins.ts]: 有考虑过替换的场景吗？这个场景也有类似的问题
