### PR TITLE
fix: Fixed the problem that when the hot area for sorting is the enti…

### LINKED ISSUE #2802: [BUG] Table 的列中同时开启 sorter 和 resize时候，resize 结束后，会触发意外的一次 sorter
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Which Component

Table

### Semi Version

2.78.0

### Current Behavior

Image

### Expected Behavior

resize结束后不会触发意料之外的排序行为

### Steps To Reproduce

https://semi.bytedance.net/zh-CN/show/table#%E5%8F%AF%E4%BC%B8%E7%BC%A9%E5%88%97

### ReproducibleCode

```markdown

```

### Environment

```markdown
- OS:
- browser:
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by YyumeiZhang**
…re table header, an unexpected sorting problem will be triggered after the expansion is completed

[中文模板 / Chinese Template](https://github.com/DouyinFE/semi-design/blob/main/.github/PULL_REQUEST_TEMPLATE.zh-CN.md)

- [x] I have read and followed [Pull Request Guidelines](https://github.com/DouyinFE/semi-design/blob/main/CONTRIBUTING-en-US.md#pull-request-guidelines) of the contributing guide.

### What kind of change does this PR introduce? (check at least one)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update
 - [ ] Refactor
 - [ ] Test Case
 - [ ] TypeScript definition update
 - [ ] Document improve
 - [ ] CI/CD improve
 - [ ] Branch sync
 - [ ] Other, please describe:

### PR description

Fixes #2802 

### Changelog
🇨🇳 Chinese
- Fix: 修复在排序热区为整个表头时候，在伸缩结束后，会触发意外的排序问题 #2802 

---

🇺🇸 English
- Fix: Fixed the problem that when the hot area for sorting is the entire table header, an unexpected sorting problem will be triggered after the expansion is completed. #2802 

### Checklist
- [ ] Test or no need
- [ ] Document or no need
- [ ] Changelog or no need

### Other
- [ ] Skip Changelog

### CODE REVIEW

File: packages/semi-foundation/table/foundation.ts [hunk 1]
```diff
@@ -1081,6 +1081,10 @@ class TableFoundation<RecordType> extends BaseFoundation<TableAdapter<RecordType
      */
     handleSort(column: { dataIndex?: string; sortOrder?: BaseSortOrder } = {}, e: any) {
         this.stopPropagation(e);
+        // if click on the resizable handle, do not trigger the sorting，fix #2802
+        if (e.target.className.includes('react-resizable-handle')) {
```
Comment (shijiatongxue) [inline packages/semi-foundation/table/foundation.ts:1085]: 兜一下 target 拿不到的场景吧

**Review by shijiatongxue — APPROVED** [review]
