### PR TITLE
fix: [Typography] fix misalignment of the icon and text of the Text c…

### LINKED ISSUE #550: [Typography] 链接按钮的icon和按钮没有垂直对齐
### Which Component 出现bug的组件
  - Button

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 

### Actual result 实际的结果是什么
  - 

### Steps to reproduce 复现步骤
  - 1

### Reproducible code 复现代码
```
 <Text link icon={<IconLink />} underline>带下划线的网页链接</Text>
```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

### PR DESCRIPTION
**Pull request by YyumeiZhang**
…omponent

[中文模板 / Chinese Template](https://github.com/DouyinFE/semi-design/blob/main/.github/PULL_REQUEST_TEMPLATE.zh-CN.md)

- [x] I have read and followed [Pull Request Guidelines](https://github.com/DouyinFE/semi-design/blob/main/CONTRIBUTING-en-US.md#pull-request-guidelines) of the contributing guide.

### What kind of change does this PR introduce? (check at least one)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update
 - [ ] Refactor
 - [ ] Test Case
 - [ ] TypeScript definition update
 - [ ] Document improve
 - [ ] CI/CD improve
 - [ ] Branch sync
 - [ ] Other, please describe:

### PR description

Fixes #550 

### Changelog
🇨🇳 Chinese
- Fix: 修复Text组件通过icon API设置icon时icon和文字不对齐问题。

---

🇺🇸 English
- Fix: fix the problem that the icon and text are not aligned when the Text component sets the icon through the icon API

### Checklist
- [x] Test or no need
- [x] Document or no need
- [x] Changelog or no need

### Other
- [ ] Skip Changelog

### CODE REVIEW

File: packages/semi-ui/typography/base.tsx [hunk 1]
```diff
@@ -72,6 +72,11 @@ const wrapperDecorations = (props: BaseTypographyProps, content: React.ReactNode
     wrap(strong, 'strong');
     wrap(props.delete, 'del');
     wrap(link, disabled ? 'span' : 'a');
+    // When the cotent is not wrapped, and there is more than one element in the conent (one of which is an icon),
```
Comment (pointhalo) [inline packages/semi-ui/typography/base.tsx:75]: cotent => content

Comment (pointhalo) [reply packages/semi-ui/typography/base.tsx:75]: conent => content

Comment (pointhalo) [reply packages/semi-ui/typography/base.tsx:75]: 前后都有一个拼写错误
