### PR TITLE
fix(table): expanded row re-render #686

### LINKED ISSUE #686: [Table] 展开行在其他行展开时会重新 render 一次
### Which Component 出现bug的组件
  - Table

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
  - 展开行在其他行展开时不要重新渲染

### Actual result 实际的结果是什么
  - 重新渲染了

### Steps to reproduce 复现步骤

1. 展开第一行
2. 展开第二行

这时第一个展开行重新渲染了。

### Reproducible code 复现代码
```
import React from 'react';
import { Table, Avatar, Descriptions, Tag } from '@douyinfe/semi-ui';
import { IconMore } from '@douyinfe/semi-icons';

const columns = [
    {
        title: '标题',
        width: 500,
        dataIndex: 'name',
        render: (text, record, index) => {
            return (
                <span>
                    <Avatar size="small" shape="square" src={record.nameIconSrc} style={{ marginRight: 12 }}></Avatar>
                    {text}
                </span>
            );
        }
    },
    {
        title: '大小',
        dataIndex: 'size',
    },
    {
        title: '所有者',
        dataIndex: 'owner',
        render: (text, record, index) => {
            return (
                <div>
                    <Avatar size="small" color={record.avatarBg} style={{ marginRight: 4 }}>
                        {typeof text === 'string' && text.slice(0, 1)}
                    </Avatar>
                    {text}
                </div>
            );
        }

    },
    {
        title: '更新日期',
        dataIndex: 'updateTime',
    },
    {
        title: '',
        dataIndex: 'operate',
    },
];

const data = [
    {
        key: '1',
        name: 'Semi Design 设计稿.fig',
        nameIconSrc: 'https://lf3-static.bytednsdoc.com/obj/eden-cn/ptlz_zlp/ljhwZthlaukjlkulzlp/figma-icon.png',
        size: '2M',
        owner: '姜鹏志',
        updateTime: '2020-02-02 05:13',
        avatarBg: 'grey'
    },
    {
        key: '2',
        name: 'Semi Design 分享演示文稿',
        nameIconSrc: 'https://lf3-static.bytednsdoc.com/obj/eden-cn/ptlz_zlp/ljhwZthlaukjlkulzlp/docs-icon.png',
        size: '2M',
        owner: '郝宣',
        updateTime: '2020-01-17 05:31',
        avatarBg: 'red'
    },
    {
        key: '3',
        name: '设计文档',
        nameIconSrc: 'https://lf3-static.bytednsdoc.com/obj/eden-cn/ptlz_zlp/ljhwZthlaukjlkulzlp/docs-icon.png',
        size: '34KB',
        owner: 'Zoey Edwards',
        updateTime: '2020-01-26 11:01',
        avatarBg: 'light-blue'
    },
];

const expandData = {
    '0': [
        { key: '实际用户数量', value: '1,480,000' },
        { key: '7天留存', value: '98%' },
        { key: '安全等级', value: '3级' },
        { key: '垂类标签', value: <Tag style={{ margin: 0 }}>设计</Tag> },
        { key: '认证状态', value: '未认证' },
    ],
    '1': [
        { key: '实际用户数量', value: '2,480,000' },
        { key: '7天留存', value: '90%' },
        { key: '安全等级', value: '1级' },
        { key: '垂类标签', value: <Tag style={{ margin: 0 }}>模板</Tag> },
        { key: '认证状态', value: '已认证' },
    ],
    '2': [
        { key: '实际用户数量', value: '2,920,000' },
        { key: '7天留存', value: '98%' },
        { key: '安全等级', value: '2级' },
        { key: '垂类标签', value: <Tag style={{ margin: 0 }}>文档</Tag> },
        { key: '认证状态', value: '已认证' },
    ]
};

function App() {

    const expandRowRender = (record, index) => {
        console.log('render', index);
        return <Descriptions align="justify" data={expandData[index]} />
    };

    const rowSelection = {
        getCheckboxProps: record => ({
            disabled: record.name === '设计文档', // Column configuration not to be checked
            name: record.name,
        }),
        onSelect: (record, selected) => {
            console.log(`select row: ${selected}`, record);
        },
        onSelectAll: (selected, selectedRows) => {
            console.log(`select all rows: ${selected}`, selectedRows);
        },
        onChange: (selectedRowKeys, selectedRows) => {
            console.log(`selectedRowKeys: ${selectedRowKeys}`, 'selectedRows: ', selectedRows);
        },
    };

    return <Table rowKey="name" columns={columns} dataSource={data} expandedRowRender={expandRowRender} rowSelection={rowSelection} pagination={false} />;
}

render(App);
```

### Additional information 补充说明
- 遇到这个bug的业务场景、上下文、或者你的需求场景

### PR DESCRIPTION
**Pull request by shijiatongxue**
[中文模板 / Chinese Template](https://github.com/DouyinFE/semi-design/blob/main/.github/PULL_REQUEST_TEMPLATE.zh-CN.md)

- [x] I have read and followed [Pull Request Guidelines](https://github.com/DouyinFE/semi-design/blob/main/CONTRIBUTING-en-US.md#pull-request-guidelines) of the contributing guide.

### What kind of change does this PR introduce? (check at least one)

 - [x] Bugfix

### PR description

Fixes #686

### Changelog
🇨🇳 Chinese
- Fix: 修复 Table 展开任意行时其他展开行会重复渲染问题 #686

---

🇺🇸 English
- Fix: Fixed the problem that when Table expands any row, other expanded rows will be rendered repeatedly #686

### Checklist
- [x] Test or no need

### Other
- [ ] Skip Changelog

### CODE REVIEW

**Review by DaiQiangReal — APPROVED** [review]

File: packages/semi-ui/table/Body/index.tsx [hunk 1]
```diff
@@ -494,7 +500,14 @@ class Body extends BaseComponent<BodyProps, BodyState> {
...
 
         const { flattenedColumns, getCellWidths } = this.context;
-        const cellWidths = getCellWidths(flattenedColumns);
+
+        // we use memoized cellWidths to avoid re-render expanded row (fix #686)
+        let cellWidths = this.cellWidths;
+        if (flattenedColumns !== this.flattenedColumns) {
+            this.flattenedColumns = flattenedColumns;
+            cellWidths = getCellWidths(flattenedColumns);
+            this.cellWidths = cellWidths;
```
Comment (pointhalo) [inline packages/semi-ui/table/Body/index.tsx:509]: 补充说明：ExpandedRow会做memo，在之前的写法中每次render时 props.cellWidths 都是新的引用，因此会导致memo无效，触发重新渲染。这次改动将其改为同一个引用，若flattenedColumns不变则无需重新计算。

File: packages/semi-ui/table/Body/index.tsx [hunk 2]
```diff
@@ -494,7 +500,14 @@ class Body extends BaseComponent<BodyProps, BodyState> {
         }
 
         const { flattenedColumns, getCellWidths } = this.context;
-        const cellWidths = getCellWidths(flattenedColumns);
+
+        // we use memoized cellWidths to avoid re-render expanded row (fix #686)
+        let cellWidths = this.cellWidths;
```
Comment (pointhalo) [inline packages/semi-ui/table/Body/index.tsx:505]: 不需要额外声明let，511行直接用 this.cellWidths 即可。
