### PR TITLE
fix(rating): size props working error when set number #356

### LINKED ISSUE #356: 【Rating】size 设置 number 后样式错误
### Which Component 出现bug的组件
  - Rating

### semi-ui version
  - latest
    
### Expected result 期望的结果是什么
 
image

### Actual result 实际的结果是什么
image

### Steps to reproduce 复现步骤
  - 看下面的复现代码

### Reproducible code 复现代码
```
<Rating defaultValue={5} size={50}/>
```

### Additional information 补充说明
设置 size 为 number 后，icon 的大小不符合预期

### PR DESCRIPTION
**Pull request by tank0317**
[中文模板 / Chinese Template](https://github.com/DouyinFE/semi-design/blob/main/.github/PULL_REQUEST_TEMPLATE.zh-CN.md)

- [x] I have read and followed [Pull Request Guidelines](https://github.com/DouyinFE/semi-design/blob/main/CONTRIBUTING-en-US.md#pull-request-guidelines) of the contributing guide.

### What kind of change does this PR introduce? (check at least one)

 - [x] Bugfix

### PR description

Fixes #356 

### Changelog
🇨🇳 Chinese
- 修复 Rating 组件设置 size 为 number 后 UI 错误

---

🇺🇸 English
- Fix Rating UI error when set size number

### Checklist
- [x] Test or no need
- [x] Document or no need
- [x] Changelog or no need

### Additional information

demo
```
<Rating defaultValue={5} size={50}/>
```

### CODE REVIEW

File: packages/semi-ui/rating/item.tsx [hunk 1]
```diff
@@ -88,7 +88,10 @@ export default class Item extends PureComponent<RatingItemProps> {
             height: size,
             fontSize: size
         } : {};
-        const iconSize = size === 'small' ? 'default' : 'extra-large';
+        
+        // when set custom size, no need a builtin style for icon, so here wo set iconSize a empty value.
```
Comment (DaiQiangReal) [inline packages/semi-ui/rating/item.tsx:92]: wo => we ？

File: packages/semi-ui/rating/item.tsx [hunk 2]
```diff
@@ -88,7 +88,10 @@ export default class Item extends PureComponent<RatingItemProps> {
...
+        const iconSize = isCustomSize ? 'empty-value' : (size === 'small' ? 'default' : 'extra-large');
+        // @ts-ignore
```
Comment (DaiQiangReal) [inline packages/semi-ui/rating/item.tsx:94]: @pointhalo 这里

**Comment by tank0317** [comment]
pending until icon support size 'inherit' #360
