### PR TITLE
fix: [Image] Fix the image is not loaded normally when the src in Ima…

### LINKED ISSUE #1526: [BUG] <Image> 远程获取Src, 懒加载机制会导致图片无法显示
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Which Component

Image

### Semi Version

2.31.0

### Current Behavior

image

### Expected Behavior

image

### Steps To Reproduce

复制代码到官网代码编辑区

### ReproducibleCode

```markdown
export const issue = () => {
    const [src, setSrc] = useState([]);
    const [previewKey, setPreviewKey] = useState('1');
    const srcList1 = [
        "https://lf3-static.bytednsdoc.com/obj/eden-cn/ptlz_zlp/ljhwZthlaukjlkulzlp/root-web-sites/lion.jpeg",
        "https://lf3-static.bytednsdoc.com/obj/eden-cn/ptlz_zlp/ljhwZthlaukjlkulzlp/root-web-sites/seaside.jpeg",
        "https://lf3-static.bytednsdoc.com/obj/eden-cn/ptlz_zlp/ljhwZthlaukjlkulzlp/root-web-sites/beach.jpeg",
    ];

    // 模拟远程加载
    useEffect(() => {
       setTimeout(() => {
        setSrc(srcList1);
       }, 1000);
    }, []);

    return (
        // src.length ?
        <ImagePreview zIndex={1000} >
            {src.map((file, index) => (
                <div
                    style={{
                        position: 'relative',
                        cursor: 'pointer',
                        display: 'inline-block',
                    }}
                    key={file}
                >
                    <Image key={file} src={file} width={96} height={96} />
                    {
                        <IconClear
                            style={{
                                position: 'absolute',
                                top: 5,
                                right: 5,
                                color: 'rgb(74, 70,70)',
                                cursor: 'pointer'
                            }}
                            onClick={()=>{
                                console.log('click');
                            }}
                        />
                    }
                </div>
            ))}
        </ImagePreview>
        //  : null
    )
}
```

### Environment

```markdown
- OS:
- browser:
```

### Anything else?

https://github.com/DouyinFE/semi-design/blob/v2.31.2/packages/semi-ui/image/preview.tsx#L87， 代码懒加载的逻辑放在了 componentDidMount中，导致如果远程加载数据，此处在 componentDidMount 阶段获取到的 allElement 为空

### PR DESCRIPTION
**Pull request by YyumeiZhang**
…ge changes in lazy loading mode

[中文模板 / Chinese Template](https://github.com/DouyinFE/semi-design/blob/main/.github/PULL_REQUEST_TEMPLATE.zh-CN.md)

- [x] I have read and followed [Pull Request Guidelines](https://github.com/DouyinFE/semi-design/blob/main/CONTRIBUTING-en-US.md#pull-request-guidelines) of the contributing guide.

### What kind of change does this PR introduce? (check at least one)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update
 - [ ] Refactor
 - [ ] Test Case
 - [ ] TypeScript definition update
 - [ ] Document improve
 - [ ] CI/CD improve
 - [ ] Branch sync
 - [ ] Other, please describe:

### PR description

Fixes #1526 

### Changelog
🇨🇳 Chinese
- Fix: 修复懒加载模式下 Image 的 src 变化，图片无法正常加载问题 #1526 

---

🇺🇸 English
- Fix: Fix the problem that the src of Image changes in lazy loading mode, and the image cannot be loaded normally.

### Checklist
- [x] Test or no need
- [x] Document or no need
- [x] Changelog or no need

### Other
- [ ] Skip Changelog

### Additional information

懒加载使用的是 IntersectionObserver， 原来的方式是在 preivew 层的 componentDidmout 去找到所有的 img元素，加入observe，此方式对 src 变化不友好（比如远程加载，修改src）

修改：
1. new 出来的 IntersectionObserver在 Preview的constructor中，通过 context 传给子组件
2. 在 Image 中 componentdidMout / componentdidUpdate 中查看 src 是否更新，将子组件注册给 observer

### CODE REVIEW

File: packages/semi-ui/image/image.tsx [hunk 1]
```diff
@@ -80,6 +82,22 @@ export default class Image extends BaseComponent<ImageProps, ImageStates> {
         return willUpdateStates;
     }
 
+    componentDidMount() {
+        this.observeImage();
+    }
+
+    componentDidUpdate(prevProps: ImageProps, prevState: ImageStates) {
+        prevProps.src !== this.props.src && this.observeImage();
```
Comment (pointhalo) [inline packages/semi-ui/image/image.tsx:90]: isEqual 合理一点？

Comment (YyumeiZhang) [reply packages/semi-ui/image/image.tsx:90]: 在Image 组件中，src 是 string类型，我理解可以直接用全等进行判断
